brew 'node'
brew 'bash'
brew 'coreutils' #macos bundled are outdated
brew 'git'
brew 'grep'
brew 'nvm'
brew 'neovim'
brew 'python3'
brew 'ripgrep'

brew 'zsh'
brew 'zsh-completions'
brew 'zsh-autosuggestions'
brew 'zsh-completions'
brew 'zsh-history-substring-search'
brew 'zsh-syntax-highlighting'

cask 'alfred'
cask 'firefox'
cask 'chromium'
cask 'iterm2'
cask 'sublime-text'
cask 'visual-studio-code'

# Fonts
brew tap homebrew/cask-fonts
brew cask install font-juliamono
cask 'font-lato'
cask 'font-open-sans'
cask 'font-roboto'
cask 'font-source-code-pro-for-powerline'
cask 'font-source-code-pro'
cask 'font-source-sans-pro'
cask 'font-source-serif-pro'
cask 'font-source-julia-mono'

tap 'caskroom/cask'
